ministryofjustice/hmpps-env-configs

- .gitignore
- generate_secrets.yml
- local_tasks/run_generation.yml
- run_generation.yml
Playbook to automagic the credential creation
> Added play to autogenerate credentials

- delius-core-dev/sub-projects/alfresco.tfvars
> Added BCL IPs to alfresco whitelist

- delius-core-dev/sub-projects/alfresco.tfvars
> Updated Alfresco AMI

- delius-core-dev/sub-projects/alfresco.tfvars
> Reduced AZ 3 Alfresco to 0

- delius-core-dev/sub-projects/alfresco.tfvars
> Added alfresco_jvm_memory var

- alfresco-dev/sub-projects/alfresco.tfvars
> Az1 now runs Alfresco

- alfresco-sbx/sub-projects/alfresco.tfvars
> Updated sandbox to match alfresco dev

- common-prod/common.properties
- common-prod/common.tfvars
- common/common.properties
- common/common.tfvars
- delius-prod/delius-prod.tfvars
Prod doesn't follow the pattern so we have updated the way the domain names are generated and consumed
> Change the way our domains are generated

- delius-mis-test/sub-projects/mis.tfvars
> modified mis.tfvars

- delius-mis-test/common.properties
- mis-nart-dev/common.properties
> Issue 122 mis deployment type var

- delius-training-test/common.properties
- delius-training-test/delius-training-test.properties
> adding overides for delius-training-test vpc

- delius-mis-test/sub-projects/delius-core.tfvars
- delius-mis-test/sub-projects/mis.tfvars
> Issue126 increase delius and mis db disk sizes

- delius-training-test/sub-projects/alfresco.tfvars
> modifying amis for delius-training-test alfresco

- delius-mis-test/common.properties
> Added legacy environment var

- delius-po-test1/common.properties
- delius-po-test1/delius-po-test1.properties
> adding overides for po-test1

- delius-training-test/sub-projects/alfresco.tfvars
> Updated Alfresco ASG to 1 instance

- delius-po-test1/sub-projects/alfresco.tfvars
> Issue 146 provision alfresco po test1

- delius-po-test2/common.properties
- delius-po-test2/delius-po-test2.properties
> adding overides for po-test2

- delius-po-test1/sub-projects/delius-core.tfvars
> Issue 149 provision delius db for po test1

- delius-po-test2/sub-projects/delius-core.tfvars
> increase disk size for delius db for po-test-2

- delius-po-test2/sub-projects/alfresco.tfvars
> updated alfresco.tfvars for po-test-2

- delius-core-dev/sub-projects/iaps.tfvars
- delius-mis-test/sub-projects/iaps.tfvars
> Adding IAPS to mis-test

- alfresco-dev/sub-projects/alfresco.tfvars
- alfresco-sbx/sub-projects/alfresco.tfvars
- common/common.tfvars
- delius-core-dev/sub-projects/alfresco.tfvars
- delius-mis-test/sub-projects/mis.tfvars
- delius-training-test/sub-projects/alfresco.tfvars
- delius-training/sub-projects/alfresco.tfvars
> Issue 164 add mis lb health check

- delius-test/sub-projects/delius-core.tfvars
> increased disk size

- delius-core-dev/sub-projects/alfresco.tfvars
- delius-training-test/sub-projects/alfresco.tfvars
> Added spg broker urls

- delius-test/sub-projects/delius-core.tfvars
> modified instance type for delius-test db

- delius-po-test1/sub-projects/alfresco.tfvars
- delius-po-test2/sub-projects/alfresco.tfvars
- delius-test/sub-projects/alfresco.tfvars
- delius-training/sub-projects/alfresco.tfvars
> Added spg mq urls for alfresco

- delius-pre-prod/zone_file.yml
- delius-test/zone_file.yml
- delius-training/zone_file.yml
> Issue197 zone names

- delius-auto-test/sub-projects/delius-core.tfvars
> Added sub-project delius-core env config for delius-auto-test

- delius-auto-test/ansible/hosts
Signed-off-by: smjmoj <smjmoj@gmail.com>
> Fixed hostnames in hosts file for auto-test

- common-prod/common.tfvars
- delius-auto-test/sub-projects/delius-core.tfvars
- delius-pre-prod/sub-projects/delius-core.tfvars
- delius-prod/sub-projects/delius-core.tfvars
- delius-stage/sub-projects/delius-core.tfvars
@marcus-bcl can you look at the ansible vars for web logic on the prod and pre-prod delius-core.tfvars
Closes #225
> Issue225 dam 116 delius stage sub project config

- delius-perf/sub-projects/delius-core.tfvars
- delius-po-test1/sub-projects/delius-core.tfvars
- delius-po-test2/sub-projects/delius-core.tfvars
- delius-pre-prod/sub-projects/delius-core.tfvars
- delius-prod/sub-projects/delius-core.tfvars
- delius-stage/sub-projects/delius-core.tfvars
- delius-test/sub-projects/delius-core.tfvars
- delius-training-test/sub-projects/delius-core.tfvars
- delius-training/sub-projects/delius-core.tfvars
> Issue230 dam 123 add delius perf config

- common/common.tfvars
> Added elasticsearch var

- delius-auto-test/common.properties
> adding delius-auto-test mis deployment type

- delius-auto-test/ansible/group_vars/all.yml
- delius-auto-test/sub-projects/delius-core.tfvars
- delius-core-dev/ansible/group_vars/all.yml
- delius-core-dev/sub-projects/delius-core.tfvars
- delius-core-sandpit/ansible/group_vars/all.yml
- delius-core-sandpit/sub-projects/delius-core.tfvars
- delius-mis-test/ansible/group_vars/all.yml
- delius-mis-test/sub-projects/delius-core.tfvars
- delius-perf/ansible/group_vars/all.yml
- delius-perf/sub-projects/delius-core.tfvars
- delius-po-test1/ansible/group_vars/all.yml
- delius-po-test1/sub-projects/delius-core.tfvars
- delius-po-test2/ansible/group_vars/all.yml
- delius-po-test2/sub-projects/delius-core.tfvars
- delius-pre-prod/ansible/group_vars/all.yml
- delius-pre-prod/sub-projects/delius-core.tfvars
- delius-prod/ansible/group_vars/all.yml
- delius-prod/sub-projects/delius-core.tfvars
- delius-stage/ansible/group_vars/all.yml
- delius-stage/sub-projects/delius-core.tfvars
- delius-test/ansible/group_vars/all.yml
- delius-test/sub-projects/delius-core.tfvars
- delius-training-test/ansible/group_vars/all.yml
- delius-training-test/sub-projects/delius-core.tfvars
- delius-training/ansible/group_vars/all.yml
- delius-training/sub-projects/delius-core.tfvars
> Issue238 dam 143 decouple ndelius versionform tf

- delius-mis-test/common.properties
> remove mis deployment type from envconfigs

- common-prod/common.credentials.yml
- common/common.credentials.yml
Set password length limit to 16.
For all the existing database and ldap passwords.
Closes #264
> Removed the temporary hard code password values.

- common-prod/common.credentials.yml
- common/common.credentials.yml
> Added the MIS DB creds

- delius-mis-test/sub-projects/mis.tfvars
> define instance type in mis.tfvars

- delius-mis-test/sub-projects/mis.tfvars
> add deploy_node var

- delius-auto-test/ansible/hosts
> Fixed error in domain name

- delius-auto-test/sub-projects/spg.tfvars
- delius-core-dev/sub-projects/spg.tfvars
- delius-core-sandpit/sub-projects/spg.tfvars
- delius-perf/sub-projects/spg.tfvars
- delius-po-test1/sub-projects/spg.tfvars
- delius-po-test2/sub-projects/spg.tfvars
- delius-pre-prod/sub-projects/spg.tfvars
- delius-prod/sub-projects/spg.tfvars
- delius-stage/sub-projects/spg.tfvars
- delius-test/sub-projects/spg.tfvars
- delius-training-test/sub-projects/spg.tfvars
- delius-training/sub-projects/spg.tfvars
Syncronised all enviros with delius-auto-test
Please note most enviros are not using their FQDN as they don't have the certificates provisioned yet
> applied latest configs across all environments

- common-prod/common.credentials.yml
- common/common.credentials.yml
> Added alfresco rds creds

- alfresco-dev/alfresco-dev.credentials.yml
- alfresco-sbx/alfresco-sbx.credentials.yml
> Issue 300 add secrets alfresco dev

- delius-auto-test/sub-projects/alfresco.tfvars
- delius-core-sandpit/sub-projects/alfresco.tfvars
- delius-perf/sub-projects/alfresco.tfvars
- delius-po-test1/sub-projects/alfresco.tfvars
- delius-po-test2/sub-projects/alfresco.tfvars
- delius-test/sub-projects/alfresco.tfvars
- delius-training-test/sub-projects/alfresco.tfvars
- delius-training/sub-projects/alfresco.tfvars
> Enable alfresco restore variable

- common/common.credentials.yml
> Added rman_password for shared system user rman catalog backups.

- delius-prod/ansible/hosts
> Amended the prod dns hosts in Ansible hosts

- common-prod/common.tfvars
- common/common.tfvars
> Added Alfresco sqs backup config

- delius-auto-test/sub-projects/new-tech.tfvars
- delius-core-dev/sub-projects/new-tech.tfvars
- delius-core-sandpit/sub-projects/new-tech.tfvars
- delius-perf/sub-projects/new-tech.tfvars
- delius-po-test1/sub-projects/new-tech.tfvars
- delius-po-test2/sub-projects/new-tech.tfvars
- delius-pre-prod/sub-projects/new-tech.tfvars
- delius-prod/sub-projects/new-tech.tfvars
- delius-stage/sub-projects/new-tech.tfvars
- delius-test/sub-projects/new-tech.tfvars
- delius-training-test/sub-projects/new-tech.tfvars
- delius-training/sub-projects/new-tech.tfvars
placeholder config map for the new tech pdf generator service
> Add initial new tech pdf generator config for all envs

- delius-auto-test/sub-projects/new-tech.tfvars
- delius-core-sandpit/sub-projects/new-tech.tfvars
- delius-perf/sub-projects/new-tech.tfvars
- delius-po-test1/sub-projects/new-tech.tfvars
- delius-po-test2/sub-projects/new-tech.tfvars
- delius-pre-prod/sub-projects/new-tech.tfvars
- delius-prod/sub-projects/new-tech.tfvars
- delius-stage/sub-projects/new-tech.tfvars
- delius-test/sub-projects/new-tech.tfvars
- delius-training-test/sub-projects/new-tech.tfvars
- delius-training/sub-projects/new-tech.tfvars
> add per env db taf config

- delius-mis-test/sub-projects/mis.tfvars
> adding http-fs vars for mis-test

- common-prod/common.tfvars
- common/common.tfvars
> Added elk and alfresco s3 bucket lifecycle vars

- alfresco-dev/sub-projects/alfresco.tfvars
- common-prod/common.tfvars
- common/common.tfvars
- delius-auto-test/sub-projects/alfresco.tfvars
- delius-prod/sub-projects/alfresco.tfvars
> Issue 341 update prod env instances sizes

- delius-mis-test/sub-projects/mis.tfvars
> remove http-fs vars

- delius-pre-prod/sub-projects/mis.tfvars
- delius-prod/sub-projects/mis.tfvars
> set bws server instance type right in preprod and prod

- alfresco-dev/sub-projects/alfresco.tfvars
- alfresco-sbx/sub-projects/alfresco.tfvars
- delius-auto-test/sub-projects/alfresco.tfvars
- delius-core-dev/sub-projects/alfresco.tfvars
- delius-perf/sub-projects/alfresco.tfvars
- delius-po-test1/sub-projects/alfresco.tfvars
- delius-po-test2/sub-projects/alfresco.tfvars
- delius-pre-prod/sub-projects/alfresco.tfvars
- delius-prod/sub-projects/alfresco.tfvars
- delius-stage/sub-projects/alfresco.tfvars
- delius-test/sub-projects/alfresco.tfvars
- delius-training-test/sub-projects/alfresco.tfvars
- delius-training/sub-projects/alfresco.tfvars
> Updated Alfresco ami to use vti_bin.war file

- common-prod/common.credentials.yml
- common/common.credentials.yml
> create newtech serach kibana webops user secret parameter

- delius-pre-prod/sub-projects/delius-core.tfvars
- delius-prod/sub-projects/delius-core.tfvars
adds new prod endpoint for offloc service
switches preprod to test mode due to offloc service being a prod only service
> dss batch job config changes for prod and preprod

- common-prod/common.tfvars
- delius-pre-prod/sub-projects/delius-core.tfvars
- delius-prod/sub-projects/delius-core.tfvars
> add JAVA_OPTS override to prod dss client config

- delius-pre-prod/sub-projects/alfresco.tfvars
- delius-prod/sub-projects/alfresco.tfvars
> Set correct instance sizes

- common-prod/common.properties
- common/common.properties
> removed the source code hash as was deemed noise and of low value

- common-prod/common.tfvars
- common/common.tfvars
> Added ELK EFS config

- common-prod/common.tfvars
- common/common.tfvars
> Updated ES admin config

- common-prod/common.tfvars
- delius-prod/sub-projects/delius-core.tfvars
> prod config updates for shared ecs cluster and nomis_url value

- delius-prod/sub-projects/new-tech.tfvars
plans tested locally - look ok
closes #404
> prod sizing for new tech

- common-prod/common.tfvars
- common/common.tfvars
> Issue 409 add es admin prod config

- common-prod/common.tfvars
> Updated elk block device

- common-prod/common.tfvars
- common/common.tfvars
- delius-auto-test/sub-projects/alfresco.tfvars
- delius-core-dev/sub-projects/alfresco.tfvars
- delius-core-sandpit/sub-projects/alfresco.tfvars
- delius-perf/sub-projects/alfresco.tfvars
- delius-po-test1/sub-projects/alfresco.tfvars
- delius-po-test2/sub-projects/alfresco.tfvars
- delius-pre-prod/sub-projects/alfresco.tfvars
- delius-prod/sub-projects/alfresco.tfvars
- delius-stage/sub-projects/alfresco.tfvars
- delius-test/sub-projects/alfresco.tfvars
- delius-training-test/sub-projects/alfresco.tfvars
> Added Alfresco RDS properties

- common-prod/common.tfvars
- common/common.tfvars
> Add I2N (IAPS Provider) Public CIDR to delius access list

- common-prod/common.tfvars
- common/common.tfvars
> Amended I2N cidr as per Rob's update

- delius-prod/sub-projects/iaps.tfvars
> Add prod iaps psn proxy config value

- common-prod/common.tfvars
- delius-perf/sub-projects/alfresco.tfvars
- delius-pre-prod/sub-projects/alfresco.tfvars
- delius-prod/sub-projects/alfresco.tfvars
> Added logstash and kibana to migration

- common-prod/common.tfvars
This allows the Zaizi London office access to production environments.
> Adding the Zaizi London office.

- common-prod/common.tfvars
- common/common.tfvars
> Updated rds engine version

- common-prod/common.credentials.yml
- common/common.credentials.yml
Create ssm parameter secret string for new tech community api appinsights key
> add appinsights key secret parameter for newtech offender api

- alfresco-dev/sub-projects/alfresco.tfvars
- alfresco-sbx/sub-projects/alfresco.tfvars
> Added alfresco dev ami blank var

- alfresco-dev/sub-projects/alfresco.tfvars
- alfresco-sbx/sub-projects/alfresco.tfvars
> blanked out var

- common-prod/common.tfvars
> Updated prod settings

- common-prod/common.credentials.yml
- common/common.credentials.yml
tested nonprod config via branch in sandpit ok
> Add secret for new tech web google analytics id

- common-prod/common.tfvars
- delius-pre-prod/sub-projects/alfresco.tfvars
- delius-prod/sub-projects/alfresco.tfvars
> Updated migration elk config

- common/common.tfvars
> Staggered update

- common-prod/common.tfvars
> Updated Al rds engines

- common-prod/common.tfvars
> Added prod backup bucket details

- common-prod/common.credentials.yml
- common/common.credentials.yml
> Added ELK htpasswd creds

- delius-po-test2/sub-projects/spg.tfvars
- delius-test/sub-projects/spg.tfvars
master branch = "latest" image version
> Dam 464 use master branch in envs where possible

- common-prod/common.tfvars
- common/common.tfvars
> Updated log retentions for Alfresco

- delius-training-test/sub-projects/alfresco.tfvars
- delius-training/sub-projects/alfresco.tfvars
> Removed AMI ID

- ansible/ansible.cfg
(see https://www.jeffgeerling.com/blog/2018/use-ansibles-yaml-callback-plugin-better-cli-experience)
> Updated to use yaml callback for output

- common-prod/common.tfvars
- delius-pre-prod/sub-projects/alfresco.tfvars
- delius-prod/sub-projects/alfresco.tfvars
> Added min_elb_capacity var for Alfresco and RDS engine update

- common-prod/common.tfvars
- delius-auto-test/sub-projects/alfresco.tfvars
- delius-core-dev/sub-projects/alfresco.tfvars
- delius-core-sandpit/sub-projects/alfresco.tfvars
- delius-perf/sub-projects/alfresco.tfvars
- delius-po-test1/sub-projects/alfresco.tfvars
- delius-po-test2/sub-projects/alfresco.tfvars
- delius-pre-prod/sub-projects/alfresco.tfvars
- delius-prod/sub-projects/alfresco.tfvars
- delius-stage/sub-projects/alfresco.tfvars
- delius-test/sub-projects/alfresco.tfvars
> Issue 548 alf update delius test ami

- common-prod/common.tfvars
Closes #555 
**Delius-Core-Dev AMI**
AMI ID - HMPPS Alfresco master 1573035871 (ami-0324358f836834251)
> Updated prod and preprod ami versions

- delius-auto-test/sub-projects/spg.tfvars
- delius-core-dev/sub-projects/mis.tfvars
- delius-core-dev/sub-projects/spg.tfvars
- delius-core-sandpit/sub-projects/spg.tfvars
- delius-perf/sub-projects/spg.tfvars
- delius-po-test1/sub-projects/mis.tfvars
- delius-po-test1/sub-projects/spg.tfvars
- delius-po-test2/sub-projects/mis.tfvars
- delius-po-test2/sub-projects/spg.tfvars
- delius-pre-prod/sub-projects/spg.tfvars
- delius-prod/sub-projects/spg.tfvars
- delius-stage/sub-projects/spg.tfvars
- delius-test/sub-projects/spg.tfvars
- delius-training-test/sub-projects/spg.tfvars
- delius-training/sub-projects/mis.tfvars
- delius-training/sub-projects/spg.tfvars
- mis-nart-test/sub-projects/mis.tfvars
Reverts ministryofjustice/hmpps-env-configs#553
> Revert "removed errorenously named and unused variable eng-remote_state_bucke…"

- common-prod/common.tfvars
The IP address has changed and I can use the MoJ VPN or bastions for
access.
> Removing Byers from the allow list.

- delius-po-test1/sub-projects/delius-core.tfvars
> Increased po-test1 Delius DB disk size for IFSR3 migration

- alfresco-dev/sub-projects/alfresco.tfvars
- common-prod/common.tfvars
- common/common.tfvars
- delius-auto-test/sub-projects/alfresco.tfvars
- delius-core-dev/sub-projects/alfresco.tfvars
- delius-core-sandpit/sub-projects/alfresco.tfvars
- delius-perf/sub-projects/alfresco.tfvars
- delius-po-test1/sub-projects/alfresco.tfvars
- delius-po-test2/sub-projects/alfresco.tfvars
- delius-stage/sub-projects/alfresco.tfvars
- delius-test/sub-projects/alfresco.tfvars
- delius-training-test/sub-projects/alfresco.tfvars
- delius-training/sub-projects/alfresco.tfvars
> Issue 563 add alf ami name var

- delius-po-test1/delius-po-test1.properties
- delius-po-test1/delius-po-test1.tfvars
- delius-po-test1/sub-projects/delius-core.tfvars
- delius-po-test1/sub-projects/parent-orgs.tfvars
- delius-po-test1/sub-projects/spg.tfvars
> Dam 584 update po test1 strategic zone to po test

- delius-po-test1/sub-projects/alfresco.tfvars
> set potest1 es snapshot name

- delius-pre-prod/ansible/group_vars/all.yml
> Set delius version to 4.4.8.1 patch version in PRE-PROD

- common-prod/common.tfvars
- common/common.tfvars
> Rolled back to Alfresco db to 9.6.9

- delius-test/ansible/group_vars/all.yml
> Update delius-test to ndelius patch 4.4.8.1

- delius-core-dev/sub-projects/mis.tfvars
- delius-mis-test/sub-projects/mis.tfvars
- delius-pre-prod/sub-projects/mis.tfvars
- delius-prod/sub-projects/mis.tfvars
> adding enhanced montoring and db size

- delius-test/sub-projects/alfresco.tfvars
> Updated AMI image name

- delius-po-test1/sub-projects/alfresco.tfvars
Closes #605 
Alfresco potest1 release
> Updated potest1 ami

- common/common.tfvars
> Added alfresco release pipeline config

- common-prod/common.tfvars
- common/common.tfvars
- delius-pre-prod/sub-projects/alfresco.tfvars
> PreProd uplift

- common/common.tfvars
- delius-training/sub-projects/alfresco.tfvars
> Update training version

- delius-pre-prod/sub-projects/alfresco.tfvars
- delius-stage/sub-projects/alfresco.tfvars
> Added cross account var

- delius-pre-prod/sub-projects/spg.tfvars
- delius-stage/sub-projects/spg.tfvars
I think we should merge this branch into master - it contains the new 0-9-14 PO mappings for test and the updates to pull the "latest" image in all envs
Then I will create a new official SR17a release branch off of master
> Release spg 2.4.11

- delius-prod/sub-projects/alfresco.tfvars
> Instance updated to reflect manual changes done earlier

- common-prod/common.tfvars
- delius-po-test1/sub-projects/alfresco.tfvars
- delius-pre-prod/sub-projects/alfresco.tfvars
- delius-stage/sub-projects/alfresco.tfvars
- delius-test/sub-projects/alfresco.tfvars
- delius-training/sub-projects/alfresco.tfvars
> Alfresco 3.4.11 release into stage, preprod nad stage

- delius-mis-dev/delius-mis-dev.tfvars
> Fixed the delius-mis-dev cidr

- delius-mis-dev/zone_file.yml
> set the correct parent account id

- delius-mis-dev/sub-projects/delius-core.tfvars
> Added the variables for the DSS batch job.

- alfresco-dev/sub-projects/alfresco.tfvars
- common-prod/common.tfvars
- common/common.tfvars
- delius-prod/sub-projects/alfresco.tfvars
> Enabled alerting for Alf and Dev

- common-prod/common.tfvars
- common/common.tfvars
PR for Database config updates
> Added alfresco database parameters

- delius-core-dev/ansible/group_vars/all.yml
to reference and patch oracle patch 20807155 during build
> Updated delius-core-dev env config 

- delius-mis-dev/ansible/group_vars/all.yml
- delius-mis-dev/ansible/group_vars/delius_primarydb.yml
- delius-mis-dev/ansible/group_vars/delius_standbydb1.yml
- delius-mis-dev/ansible/group_vars/delius_standbydb2.yml
So the patch is only applied to delius env, not mis
> Updated the env config files for mis-dev delius_primary, standby1+2

- delius-prod/sub-projects/alfresco.tfvars
```Terraform will perform the following actions:
~ module.db_instance.aws_db_instance.inst
instance_class:                    "db.m5.12xlarge" => "db.m5.2xlarge"
~ module.parameter_group.aws_db_parameter_group.this
parameter.#:                       "7" => "10"
parameter.1758074917.apply_method: "" => "pending-reboot"
parameter.1758074917.name:         "" => "autovacuum_analyze_threshold"
parameter.1758074917.value:        "" => "20000"
parameter.2281588144.apply_method: "pending-reboot" => "pending-reboot"
parameter.2281588144.name:         "pg_stat_statements.track" => "pg_stat_statements.track"
parameter.2281588144.value:        "all" => "ALL"
parameter.2343854315.apply_method: "pending-reboot" => "pending-reboot"
parameter.2343854315.name:         "pg_stat_statements.max" => …
```
> Updated prod instance

- delius-mis-dev/sub-projects/mis.tfvars
- delius-pre-prod/sub-projects/mis.tfvars
- delius-prod/sub-projects/mis.tfvars
> adding mis dis lb healtcheck

- delius-perf/delius-perf.properties
- delius-perf/delius-perf.tfvars
- delius-perf/sub-projects/alfresco.tfvars
- delius-perf/sub-projects/delius-core.tfvars
Ensuring the size of the AWS resources match that of production to start with.
> Updating the VPC CIDR to use a production range 10.160

- delius-perf/delius-perf.tfvars
work-mem set to 16MB for Alfresco
> updated delius-perf.tfvars

- delius-stage/ansible/group_vars/all.yml
RBAC Version was already set to 4.5.3.
> Ndelius Version in State 4.5.3

- common/common.properties
- delius-auto-test/delius-auto-test.properties
- delius-auto-test/delius-auto-test.tfvars
- delius-core-dev/delius-core-dev.properties
- delius-core-dev/delius-core-dev.tfvars
- delius-core-sandpit/delius-core-sandpit.properties
- delius-core-sandpit/delius-core-sandpit.tfvars
> adding vars for autostop lambda

- delius-pre-prod/ansible/group_vars/all.yml
- delius-pre-prod/ansible/group_vars/delius_primarydb.yml
- delius-pre-prod/ansible/group_vars/delius_standbydb1.yml
- delius-pre-prod/ansible/group_vars/delius_standbydb2.yml
so jenkins knows what file to download and apply to pre-prod
> Defined the patch ID and variables 

- common-prod/common.tfvars
Don't merge until we have JIRA.
> GDPR_Version => 0.18.0

- delius-mis-dev/sub-projects/mis.tfvars
- delius-pre-prod/sub-projects/mis.tfvars
> enable mis dev and preprod alerts to non prod channel

- common-prod/common.tfvars
- common/common.tfvars
> GDPR => 0.20.0

- delius-pre-prod/sub-projects/new-tech.tfvars
- delius-prod/sub-projects/new-tech.tfvars
- delius-stage/sub-projects/new-tech.tfvars
- delius-test/sub-projects/new-tech.tfvars
Allow Prod Fortinet to access community api (secure)
> Allow Test Fortinet to access test community api (secure and non-secure)

- delius-pre-prod/sub-projects/alfresco.tfvars
Added alfresco pre prod snapshot id for pre prod refresh
> Added pre prod rds snapshot id

- common-prod/common.tfvars
- common/common.tfvars
Adding solr ebs volume for temp file location
> Added temp disk config

- delius-prod/sub-projects/alfresco.tfvars
The above will keep the instance size for prod db.m5.12xlarge
> Added instance class option to prod config

- common-prod/common.properties
- delius-perf/delius-perf.properties
Enabling autostop tag for perf
> adding autostop tag

- delius-po-test1/ansible/group_vars/all.yml
- delius-po-test1/ansible/group_vars/ldap.yml
PO Test 
NDelius => 4.6.11
RBAC => 4.5.7
> Paulmiller bcl patch 1

- delius-core-dev/sub-projects/delius-core.tfvars
- delius-test/sub-projects/delius-core.tfvars
Access to dev,
Access to "delius-test" as requested.
Closes #990
> Example of setting CI ingress rule on an env

- common-prod/common.tfvars
- delius-perf/delius-perf.tfvars
- delius-perf/sub-projects/delius-core.tfvars
- delius-pre-prod/delius-pre-prod.tfvars
- delius-pre-prod/sub-projects/delius-core.tfvars
- delius-prod/delius-prod.tfvars
- delius-prod/sub-projects/delius-core.tfvars
- delius-stage/delius-stage.tfvars
- delius-stage/sub-projects/delius-core.tfvars
Also removed some duplication.
I've tested this branch in the Perf environment (it only affects envs using common-prod.tfvars, so I was unable to use Sandpit or Dev): https://jenkins.engineering-dev.probation.hmpps.dsd.io/job/DAMS/job/Environments/job/delius-perf/job/Delius/job/Deploy_Infrastructure/23/console
> ALS-779 Reduce instance count for SPG and Interface domains in prod-like envs

- delius-core-dev/ansible/group_vars/all.yml
- delius-core-dev/sub-projects/delius-core.tfvars
- delius-core-sandpit/ansible/group_vars/all.yml
- delius-core-sandpit/sub-projects/delius-core.tfvars
- delius-int/ansible/group_vars/all.yml
- delius-int/sub-projects/delius-core.tfvars
- delius-mis-dev/ansible/group_vars/all.yml
- delius-mis-dev/sub-projects/delius-core.tfvars
- delius-mis-test/ansible/group_vars/all.yml
- delius-mis-test/sub-projects/delius-core.tfvars
- delius-perf/ansible/group_vars/all.yml
- delius-perf/sub-projects/delius-core.tfvars
- delius-po-test1/ansible/group_vars/all.yml
- delius-po-test1/sub-projects/delius-core.tfvars
- delius-pre-prod/ansible/group_vars/all.yml
- delius-pre-prod/sub-projects/delius-core.tfvars
- delius-prod/ansible/group_vars/all.yml
- delius-prod/sub-projects/delius-core.tfvars
- delius-stage/ansible/group_vars/all.yml
- delius-stage/sub-projects/delius-core.tfvars
- delius-test/ansible/group_vars/all.yml
- delius-test/sub-projects/delius-core.tfvars
- delius-training-test/ansible/group_vars/all.yml
- delius-training-test/sub-projects/delius-core.tfvars
- delius-training/ansible/group_vars/all.yml
- delius-training/sub-projects/delius-core.tfvars
- It is not used in the terraform stage
- It is used in the Ansible stages
- Want only one place where this is defined.
> Moved the HA config from the terraform config to Ansible because:

- common/common.properties
- common/common.tfvars
These fixes are required for terraform .12
Add missing commas to provisioned-with and source-code
Removed duplicate entry for es_jvm_heap_size = "8g"
> Als 891 fix common properties

- delius-po-test1/sub-projects/delius-core.tfvars
https://jira.engineering-dev.probation.hmpps.dsd.io/browse/ALS-1068
> Enable the CI to ingress on 1521 to Delius DB for PO-TEST1

- delius-pre-prod/sub-projects/alfresco.tfvars
Update pre-prod snapshot for refresh tasks
> Updated pre-prod snapshot name

- delius-test/ansible/group_vars/delius_primarydb.yml
Sometimes require reverting to older version of application for testing.
> Increase default retention for Test database from 14 to 28 days

- Makefile
- pipelines/buildspec-ansible2.yml
Add create credentials codepipeline
> Added manage secrets pipeline

- delius-po-test1/sub-projects/delius-core.tfvars
- delius-pre-prod/sub-projects/delius-core.tfvars
- delius-prod/sub-projects/delius-core.tfvars
> Allow access to PO-Test and Pre-Prod from new MTCNovo ZScaler infrastructure

- delius-perf/ansible/group_vars/all.yml
Adding extra logging to NDelius, checking the timings of the interactions with ALF API.
> NDelius => 4.7.8.7_ALFLogging

- delius-pre-prod/ansible/group_vars/ldap.yml
Includes new central reporting groups
> Deploy RBAC 4.7.12 to Pre-Prod

- common-prod/common.tfvars
- delius-pre-prod/sub-projects/alfresco.tfvars
- delius-prod/sub-projects/alfresco.tfvars
> Added pre-prod and prod settings

- delius-prod/ansible/group_vars/all.yml
> Deploy 4.7.8.10 to Production

- delius-perf/sub-projects/new-tech.tfvars
Signed-off-by: Paul Massey <paul.massey@digital.justice.gov.uk>
> Updated  delius-perf new-tech

- common-prod/common.credentials.yml
- common/common.credentials.yml
Credentials are now generated within each target account by AWS Automation/CodeBuild.
> Removed delegation for credential creation

- delius-prod/ansible/group_vars/all.yml
> NDelius => 4.8.13.3

- delius-int/sub-projects/new-tech.tfvars
- Initial settings mainly copied from the nDelius test environment
- There may be setting that are inappropriate for the integration env so have set the PR to draft pending sanity checks
> Add configuration for nDelius integration environment

- delius-pre-prod/sub-projects/new-tech.tfvars
- delius-prod/sub-projects/new-tech.tfvars
- delius-test/sub-projects/new-tech.tfvars
changes are switches on for prepared/test to allow testing to continue
changes are off in production to allow a release
> community-api feature switches for OMiC changes

- delius-core-dev/sub-projects/delius-core.tfvars
- delius-stage/sub-projects/delius-core.tfvars
- delius-test/sub-projects/delius-core.tfvars
to bypass VPD until an application-specific user has been added
> Temporarily use DELIUS_APP_SCHEMA user for Delius API

- common-prod/common.tfvars
- common/common.tfvars
- delius-core-dev/sub-projects/delius-core.tfvars
- delius-prod/sub-projects/delius-core.tfvars
- delius-stage/sub-projects/delius-core.tfvars
- delius-test/sub-projects/delius-core.tfvars
Also updated the image url with hmpps alias, 
enabled SQL logging and disabled application insights in Dev
> Update Delius-API to use DELIUS_API_POOL user for database connection

- delius-po-test1/ansible/group_vars/all.yml
Deploying in morning first thing.
> NDelius => 4.9.11.0

- delius-training/ansible/group_vars/all.yml
- delius-training/ansible/group_vars/ldap.yml
> DST-8962 Deploy NDelius 4.10.12 to Training

- delius-perf/sub-projects/delius-core.tfvars
- delius-pre-prod/sub-projects/delius-core.tfvars
Also adding configuration for the Performance environment, for consistency with other services (e.g. Community-API)
> DST-8977 Deploy Delius-API to Pre-Prod.

- cr-unpaid-work-dev/sub-projects/cporacle.tfvars
- cr-unpaid-work-prod/sub-projects/cporacle.tfvars
Fixes for Chris's TF plans in CPOracle Dev & Prod
Incorporated un-merged changes from issues/1557/ALS-3280-CPOracle-InitialStructure
> Fixes for Chris's TF plans missing variables in CPOracle Dev & Prod

- common-prod/common.tfvars
to account for larger workloads (e.g. Delius/WebLogic)
> ALS-2957 Update production ECS instance type and capacity

- common/common.tfvars
and remove CPU count override.
> Increase min_capacity for weblogic app service in non-prod envs

- common/common.tfvars
to resolve race condition on start up
> Increase WebLogic CPU in non-prod environments

- delius-core-dev/sub-projects/delius-core.tfvars
- delius-pre-prod/sub-projects/delius-core.tfvars
- delius-stage/sub-projects/delius-core.tfvars
- delius-test/sub-projects/delius-core.tfvars
to specify the OAUTH_LOGIN_ENABLED flag and remove some unneeded values
> Updated Delius OAuth config

- ansible/group_vars/all.yml
- delius-pre-prod/ansible/group_vars/all.yml
- delius-pre-prod/ansible/group_vars/ldap.yml
- delius-test/ansible/group_vars/all.yml
- delius-test/ansible/group_vars/ldap.yml
> ND => 5.1.14.3, RBAC => 5.1.9

- delius-perf/ansible/group_vars/all.yml
To test the fix for Audit Log Issues.
> NDelius => 5.1.14.4

- delius-prod/ansible/group_vars/delius_primarydb.yml
No Audited Interaction Corrections required prior to 27 April 2021
> Reset Retention to 1 Year

- cr-unpaid-work-dev/sub-projects/cporacle.tfvars
- cr-unpaid-work-prod/sub-projects/cporacle.tfvars
AMIs currently in use in dev (manually)
> Updated app and api CP Oracle servers to use latest AMIs

- delius-mis-dev/ansible/group_vars/misboe_primarydb.yml
- delius-pre-prod/ansible/group_vars/misboe_primarydb.yml
- delius-pre-prod/ansible/group_vars/misboe_standbydb1.yml
- delius-pre-prod/ansible/group_vars/misboe_standbydb2.yml
- delius-prod/ansible/group_vars/misboe_primarydb.yml
- delius-prod/ansible/group_vars/misboe_standbydb1.yml
- delius-prod/ansible/group_vars/misboe_standbydb2.yml
ALS-4454 19.12 patch 26749785 for misboe
> ALS-4454 19.12 patch 26749785 for misboe

- delius-core-dev/sub-projects/iaps.tfvars
- delius-stage/sub-projects/iaps.tfvars
Preperation for tomorrow's IM migration in stage
> IAPS Stage AMI update to latest

- delius-stage/sub-projects/iaps.tfvars
> Setting Stage back to before migration

- delius-training-test/sub-projects/alfresco.tfvars
- delius-training/sub-projects/alfresco.tfvars
Upgrade path to 11.4 is no longer available
> NIT-40 upgrade training envs to postgres 11.14

- delius-perf/delius-perf.tfvars
Comment schedule of Perf refresh now that 19.12 has been applied
> Comment schedule of Perf refresh

- cr-unpaid-work-dev/sub-projects/cporacle.tfvars
> update cporacle dev to latest ami

- delius-prod/sub-projects/iaps.tfvars
Production IM-Migration happening this weekend (19th/20th March 2022)
> IAPS Prod switch to latest AMI with new urls

- delius-core-dev/ansible/group_vars/all.yml
Rolling back one version to test New Search -> NDelius (Serious Offender popup)
> NDelius => 5.3.10

- delius-core-dev/sub-projects/delius-core.tfvars
- delius-perf/sub-projects/delius-core.tfvars
- delius-pre-prod/sub-projects/delius-core.tfvars
- delius-prod/sub-projects/delius-core.tfvars
- delius-stage/sub-projects/delius-core.tfvars
- delius-test/sub-projects/delius-core.tfvars
Values were taken from:
* https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-dev/07-certificate.yaml
* https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/07-certificate.yaml
* https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/07-certificate.yaml
> PI-149 Added URL config for pre-sentence-service.

- delius-stage/sub-projects/iaps.tfvars
Oracle 19c upgrade stage update
> Oracle 19c upgrade stage update

- delius-stage/ansible/group_vars/delius_primarydb.yml
DBA-51 Stage 19.14 env changes
> DBA-51 Stage 19.14 env changes

- delius-mis-dev/ansible/group_vars/all.yml
DBA-86 release-update only changes
> DBA-86 release-update only changes

- delius-mis-dev/ansible/group_vars/misboe_primarydb.yml
DBA-112 add 1914 version of 26749785 for MIS Dev boe
> DBA-112 add 1914 version of 26749785 for MIS Dev boe

- delius-mis-dev/ansible/group_vars/delius_primarydb.yml
DBA-48 updated env 19.14 for delius
> DBA-48 updated env 19.14 for delius

- delius-stage/ansible/group_vars/misboe_primarydb.yml
DBA-112 include 19.14 version of patch 26749785 for Stage
> DBA-112 include 19.14 version of patch 26749785 for Stage

- delius-core-sandpit/ansible/group_vars/all.yml
> DBA-86 env file for sandpit

- delius-core-dev/ansible/group_vars/all.yml
- delius-perf/ansible/group_vars/all.yml
- delius-pre-prod/ansible/group_vars/all.yml
- delius-prod/ansible/group_vars/all.yml
- delius-stage/ansible/group_vars/all.yml
- delius-test/ansible/group_vars/all.yml
- delius-training-test/ansible/group_vars/all.yml
- delius-training/ansible/group_vars/all.yml
> DBA-86 env files

- delius-mis-dev/ansible/group_vars/mis_primarydb.yml
- delius-mis-dev/ansible/group_vars/misboe_primarydb.yml
- delius-mis-dev/ansible/group_vars/misdsd_primarydb.yml
DBA-48 MIS Dev env changes 19.14
> DBA-48 MIS Dev env changes 19.14

- delius-training/delius-training.tfvars
DST-12001 Re-activate Flashback
> DST-12001 Re-activate Flashback

- delius-test/sub-projects/delius-core.tfvars
> Update to Batch Schedule for Merge

- delius-stage/sub-projects/delius-core.tfvars
DST-12115
Recover Offender - Getting an APPERR031 when selecting search
Also enable GDPR in stage.
> Enabling Merge in Stage to fix this defect in Stage.

- common-prod/common.tfvars
- common/common.tfvars
Work item: https://dsdmoj.atlassian.net/browse/NIT-206
Adding db connection pool properties (min and max) for non-prod and prod.
Reviewers! See work item for information on how the values were calculated and decided.
> Adding alfresco read/content db pool properties for non-prod and prod

- delius-pre-prod/ansible/group_vars/misboe_primarydb.yml
- delius-pre-prod/ansible/group_vars/misboe_standbydb1.yml
DBA-112 19.14 patch 26749785 for Pre-prod
> DBA-112 19.14 patch 26749785 for Pre-prod

- delius-pre-prod/ansible/group_vars/mis_standbydb1.yml
- delius-prod/ansible/group_vars/mis_standbydb1.yml
Highest value recorded is 848 seconds.
> Increase Apply Lag Threshold

- delius-pre-prod/ansible/group_vars/delius_primarydb.yml
DBA-53 env file Pre-prod 19.14
> DBA-53 env file Pre-prod 19.14

- delius-training/ansible/group_vars/delius_primarydb.yml
> DBA-56 env file for 19.14

- delius-pre-prod/ansible/group_vars/all.yml
- delius-prod/ansible/group_vars/all.yml
- delius-stage/ansible/group_vars/all.yml
> Remove Reference to Management Server

- alfresco-dev/sub-projects/alfresco.tfvars
- delius-core-dev/sub-projects/alfresco.tfvars
- delius-pre-prod/sub-projects/alfresco.tfvars
- delius-prod/sub-projects/alfresco.tfvars
- delius-stage/sub-projects/alfresco.tfvars
- delius-test/sub-projects/alfresco.tfvars
- delius-training/sub-projects/alfresco.tfvars
Work item: https://dsdmoj.atlassian.net/browse/NIT-236
Config data changes to drive the upgrades of the postgreSQL RDS alfresco-database instances from 11.4 -> 11.14.
> Incrementing alfresco-database version across environments

- delius-test/sub-projects/delius-core.tfvars
Set EBS vol throughput value to 125.
Ticket no. https://dsdmoj.atlassian.net/browse/NIT-187
> Set disk_throughput_data to 125

- delius-prod/ansible/group_vars/delius_primarydb.yml
> DBA-57 env file 19.14

- delius-pre-prod/ansible/group_vars/mis_primarydb.yml
- delius-pre-prod/ansible/group_vars/misboe_primarydb.yml
- delius-pre-prod/ansible/group_vars/misdsd_primarydb.yml
DBA-53 env file changes for 19.14 patching
> DBA-53 env file changes for 19.14 patching

- delius-prod/ansible/group_vars/misboe_primarydb.yml
- delius-prod/ansible/group_vars/misboe_standbydb1.yml
DBA-112 env file to have 19.14 version of 26749785
> DBA-112 env file to have 19.14 version of 26749785

- delius-prod/ansible/group_vars/mis_primarydb.yml
- delius-prod/ansible/group_vars/misboe_primarydb.yml
- delius-prod/ansible/group_vars/misdsd_primarydb.yml
DBA-57 MIS env files for 19.14
> DBA-57 MIS env files for 19.14

- delius-stage/ansible/group_vars/delius_primarydb.yml
DBA-205 env file for 19.16 Stage
> DBA-205 env file for 19.16 Stage

- delius-mis-dev/ansible/group_vars/delius_primarydb.yml
> DBA-201 env file for 19.16

- delius-prod/ansible/group_vars/delius_primarydb.yml
Access to production data for Analytics Platform Team
> Add Soumaya Mauthoor as Standby-Only Read-Only User

- delius-mis-dev/ansible/group_vars/misboe_primarydb.yml
DBA-220 env file include 19.16 version of 26749785 for misboe
> DBA-220 env file include 19.16 version of 26749785 for misboe

- delius-mis-dev/ansible/group_vars/mis_primarydb.yml
- delius-mis-dev/ansible/group_vars/misboe_primarydb.yml
- delius-mis-dev/ansible/group_vars/misdsd_primarydb.yml
DBA-202 MIS DEV env files to have 19.16 versions
> DBA-202 MIS DEV env files to have 19.16 versions

- ansible/group_vars/all.yml
Adds new regional reporting groups for N03 and N07.
> Deploy Delius RBAC 5.4.7

- delius-stage/ansible/group_vars/misboe_primarydb.yml
19.16 version of patch 26749785 for BOE
> 19.16 version of patch 26749785 for BOE

- delius-stage/ansible/group_vars/mis_primarydb.yml
- delius-stage/ansible/group_vars/misboe_primarydb.yml
- delius-stage/ansible/group_vars/misdsd_primarydb.yml
DBA-206 MIS env files for 19.16
> DBA-206 MIS env files for 19.16

- delius-pre-prod/ansible/group_vars/delius_primarydb.yml
DBA-208 pre-prod 19.16 env file
> DBA-208 pre-prod 19.16 env file

- delius-test/sub-projects/delius-core.tfvars
Setting GDPR and Merge to specific versions rather than latest.
GDPR => 0.27.0
Merge => 0.22.0
> Update to MS Version

- common-prod/common.properties
- common/common.properties
https://dsdmoj.atlassian.net/browse/NIT-344
Change required to upgrade aws provider version to v3 for hmpps-delius-pipelines repo
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#github_token-environment-variable-removal
> Create github_token TF var for all non prod and prod envs

- delius-pre-prod/ansible/group_vars/misboe_primarydb.yml
- delius-pre-prod/ansible/group_vars/misboe_standbydb1.yml
DBA-222 19.16 version of patch 26749785
> DBA-222 19.16 version of patch 26749785

- delius-pre-prod/ansible/group_vars/mis_primarydb.yml
- delius-pre-prod/ansible/group_vars/misboe_primarydb.yml
- delius-pre-prod/ansible/group_vars/misdsd_primarydb.yml
DBA-209 Env files for 19.16 MIS Pre-prod
> DBA-209 Env files for 19.16 MIS Pre-prod

- delius-training/ansible/group_vars/delius_primarydb.yml
DBA-204 19.16 env file Training
> DBA-204 19.16 env file Training

- delius-prod/ansible/group_vars/misboe_primarydb.yml
- delius-prod/ansible/group_vars/misboe_standbydb1.yml
DBA-223 19.16 version of patch 26749785 for boe
> DBA-223 19.16 version of patch 26749785 for boe

- delius-prod/ansible/group_vars/mis_primarydb.yml
- delius-prod/ansible/group_vars/misboe_primarydb.yml
- delius-prod/ansible/group_vars/misdsd_primarydb.yml
DBA-211 MIS env files for 19.16 Prod
> DBA-211 MIS env files for 19.16 Prod

- ansible/group_vars/all.yml
- common-prod/common.tfvars
- delius-pre-prod/sub-projects/delius-core.tfvars
- delius-prod/ansible/group_vars/all.yml
- delius-stage/sub-projects/delius-core.tfvars
Also updates RBAC to 5.5.8 and Merge to 0.23.0
> Deploy Delius 5.6.4 to Prod

- delius-mis-dev/delius-mis-dev.tfvars
- delius-mis-dev/sub-projects/mis.tfvars
- delius-prod/delius-prod.tfvars
- delius-prod/sub-projects/mis.tfvars
Ticket no. https://dsdmoj.atlassian.net/browse/NIT-409
> Create new tag for MIS ETL server for setting when resizing schedule is enabled

- delius-test/ansible/group_vars/delius_primarydb.yml
DBA-262 env file 19.18 Test Delius
> DBA-262 env file 19.18 Test Delius

- delius-mis-dev/ansible/group_vars/misboe_primarydb.yml
DBA-260 19.18 version of 26749785 for BOE
> DBA-260 19.18 version of 26749785 for BOE

- delius-mis-dev/ansible/group_vars/mis_primarydb.yml
- delius-mis-dev/ansible/group_vars/misboe_primarydb.yml
- delius-mis-dev/ansible/group_vars/misdsd_primarydb.yml
> DBA-261 env files 1918

- delius-mis-dev/ansible/group_vars/delius_primarydb.yml
> DBA-260 env file 1918

- delius-stage/ansible/group_vars/delius_primarydb.yml
> DBA-264 env file for 19.18

- delius-stage/ansible/group_vars/mis_primarydb.yml
- delius-stage/ansible/group_vars/misboe_primarydb.yml
- delius-stage/ansible/group_vars/misdsd_primarydb.yml
> DBA-265 env files for 19.18

- common-prod/common.tfvars
Ticket no. https://dsdmoj.atlassian.net/browse/NIT-567
> Resize alfresco ECS ASGs in higher envs as instances are over-provisioned

- delius-prod/sub-projects/delius-core.tfvars
Updating delius app min_capacity to 40.
> min_capacity = 40

- .github/workflows/tag-master-branch-on-merge.yaml
Add version tag for the following repo
https://github.com/anothrNick/github-tag-action/tags
> Add version to github-tag-action repo to tag repo after PR merges

- common-prod/common.tfvars
- common/common.tfvars
Also removed decommissioned NAT addresses
> Add MP NAT IPs to user access block

- delius-pre-prod/ansible/group_vars/delius_primarydb.yml
- delius-pre-prod/ansible/group_vars/mis_primarydb.yml
- delius-pre-prod/ansible/group_vars/misboe_primarydb.yml
- delius-pre-prod/ansible/group_vars/misdsd_primarydb.yml
Switch off old FSFO implementation ahead of DBA-380
> Disable Legacy Mode FSFO

- common-prod/common.tfvars
Ticket number. https://dsdmoj.atlassian.net/browse/NIT-737
> Additional MOJ owned IP ranges

- delius-pre-prod/ansible/group_vars/all.yml
- delius-pre-prod/ansible/group_vars/ldap.yml
- delius-pre-prod/sub-projects/delius-core.tfvars
Reverts ministryofjustice/hmpps-env-configs#2272
> Rollback ND in Pre-prod

- delius-pre-prod/ansible/group_vars/ldap.yml
> Update ldap.yml to 5.6.15.1

- delius-pre-prod/sub-projects/delius-core.tfvars
> Increase GDPR memory

- delius-mis-dev/ansible/group_vars/mis_primarydb.yml
Was causing an error on the dashboard: https://ministryofjustice.github.io/delius-versions-dashboard/
```
bad indentation of a mapping entry at line 17, column 3:
p36252161:
```
> Fix YAML indentation

- delius-prod/sub-projects/mis.tfvars
https://mojdt.slack.com/archives/C032BQQHJE5/p1715069407835409
> Concierge: increase capacity of mis FSx FS

- common-prod/common.tfvars
- delius-prod/ansible/group_vars/all.yml
- delius-prod/ansible/group_vars/ldap.yml
- delius-prod/sub-projects/delius-core.tfvars
- delius-stage/sub-projects/delius-core.tfvars
* Also disables Merge service until DB patch is ready
> Deploy Delius SR29 to prod

- common-prod/common.tfvars
Changing quiet hours to cover BST.
> quiet_hours => 2300-0400

- delius-pre-prod/ansible/group_vars/misdsd_primarydb.yml
- delius-prod/ansible/group_vars/misdsd_primarydb.yml
- delius-stage/ansible/group_vars/misdsd_primarydb.yml
Reduce load on DSD instances at the weekend.
> Throttle full backups of DSD database

- delius-stage/ansible/group_vars/mis_primarydb.yml
- delius-stage/ansible/group_vars/misboe_primarydb.yml
- delius-stage/ansible/group_vars/misdsd_primarydb.yml
> Patch MIS databases to 19.25

- delius-mis-dev/delius-mis-dev.tfvars
Databases shutdown ahead of decommissioning
> Disable password rotation

- ansible/group_vars/all.yml
- common-prod/common.tfvars
- common/common.tfvars
UMT -> 1.17
Merge -> 0.35
LDAP -> 6.2.5
> SR30 Prod golive
