ministryofjustice/hmpps-env-configs

- delius-core-sandpit/sub-projects/spg.tfvars
Change the MPX container to be an all-in-one SPG server to temporarily allow testing of DAM-22
until the connectivity and certificate issues have been resolved
> Temporary change of MPX container to be an all-in-one SPG server

- delius-mis-test/sub-projects/mis.tfvars
- delius-pre-prod/sub-projects/mis.tfvars
- delius-prod/sub-projects/mis.tfvars
Adds a flag for deploying secondary/tertiary instances for BCS and BPS
Parameterises the root volume size to meet requirements
Updates the instance sizes for preprod and prod to meet requirements
Config for mis-test, preprod and prod e…nvs only for now
> Additional config for mis deployments 

- common-prod/common.tfvars
This should allow PSN proxies to the allow list for production
environments.
Also adding in my home for the transition and to allow testing.
> Adding PSN Proxies to prod access.

- common-prod/common.tfvars
- common/common.tfvars
This IP is used to access the interface weblogic domains for connections
to OASys.
The path is OASys -> Tibco(NDH) -> Azure API GW -> Interface load
balancer.
> Adding the IP of the Azure NDH

- ansible/group_vars/all.yml
- common/common.tfvars
First step towards separating ansible(application) variables from terraform(infrastructure) vars.
This is required for the application deployment job: https://github.com/ministryofjustice/delius-manual-deployments/pull/87
> Added initial default ansible vars into a common inventory

- delius-pre-prod/sub-projects/parent-orgs.tfvars
instigated from conversation ... https://mojdt.slack.com/archives/GNPCZF3J5/p1572450882001900
RebeccaHornby 3:54 PM
@Nic just to advise that @Paul Carvell has just noticed that we getting Alfresco messages for C04 though we believe that CRC had been made inactive? we have seen 11 messages since the application restarted about 23 ins ago
Paul Crimes 3:58 PM
we will need to disable C04 on SPG (and/or ALF) as well then - I think this is caused by CRNS / docs in ALF having an association to C04
RebeccaHornby 5:27 PM
thanks, @Paul Crimes will you be doing that or do we need to request? @Paul Carvell @Nic for info
Paul Crimes 5:35 PM
I can sort that later this eve (edited)
> updated CRC configs for Interserve in PP

- delius-core-dev/sub-projects/iaps.tfvars
updated to version currently on delius-core-dev (prob oracle upgraded via maintenance schedule)
> updated rds_engine_version = '12.1.0.2.v17'

- common-prod/common.credentials.yml
- common/common.credentials.yml
this key is so we can set the usernames to auto create when ASG creates a new IAPS appserver instance
> added iaps_local_users paramstore keys

- delius-core-dev/sub-projects/alfresco.tfvars
This change is to add config example for DLC environment.
This config will allow delius-core-dev to run a specific version if needed. 
Alfresco versions defined in common.tfvars gets updated after a release to prod.
> Allow dlc to run a specific Alf version

- common/common.tfvars
DAM-917
Plan
`Terraform will perform the following actions:
-/+ aws_security_group_rule.interface_lb_azure_oasys_ingress_tls (new resource required)
id:                       "sgrule-3644874499" => <computed> (forces new resource)
cidr_blocks.#:            "1" => "2" (forces new resource)
cidr_blocks.0:            "51.140.255.11/32" => "51.140.255.11/32"
cidr_blocks.1:            "" => "51.137.128.165/32" (forces new resource)
description:              "Azure OASys Proxy Ingress (TLS)" => "Azure OASys Proxy Ingress (TLS)"
from_port:                "443" => "443"
protocol:                 "tcp" => "tcp"
security_group_id:        "sg-0658aebd6885b382e" => "sg-0658aebd6885b382e"
self:                     "false" => "false"
source_security_group_id: "" => <computed>
to_port: …
> Adding the NDH  Bridge IP for access to the Delius Interface LB

- delius-po-test1/sub-projects/delius-core.tfvars
- delius-po-test2/sub-projects/delius-core.tfvars
- delius-pre-prod/sub-projects/delius-core.tfvars
- delius-prod/sub-projects/delius-core.tfvars
- delius-training-test/sub-projects/delius-core.tfvars
Request from ARCC was raised today due to a change in their external IP address: https://mojdt.slack.com/archives/GNVKM6ZJR/p1581409021001700
> Steven Horner  08:17
> Hello, DTVs external IP Address that would be whitelisted for both OASys and nDelius has changed. Who do I need to contact to change this urgently, currently we have no access to either.
> Update whitelisted IP range for the ARCC Parent Organisation

- delius-core-dev/sub-projects/spg.tfvars
It is controlled from the jenkins deployment jobs
> image_verson should no longer be in spg.tfvars

- common-prod/common.tfvars
Solr indexing in stage has breached 500GB
> Updated solr temp disk space size

- common-prod/common.tfvars
- common/common.tfvars
(2147483647 strconv.ParseInt: parsing "16106127360": value out of range)
> Set db_max_size to a string, as hcl-parser fails due to the value being too large when calling Go's ParseInt.

- delius-prod/zone_file.yml
Remove some whitespace, so that the commented out account_id isn't matched by the hacky regex in delius-manual-deployments. The delius-manual-deployments repo will be updated next week to handle this scenario.
> Remove some whitespace

- common-prod/common.tfvars
- common/common.tfvars
The higher values are no longer required since switching to the MDB-based backup/restore process
> ALS-1419 Reduce LDAP disk IOPS

- delius-pre-prod/sub-projects/new-tech.tfvars
- delius-prod/sub-projects/new-tech.tfvars
- delius-test/sub-projects/new-tech.tfvars
By default offender search is off everywhere, whereas by default poll pusher is off in test/preprod/prod
* Poll pushers uses a set desired count
* Offender search uses a scaling count so methods to set to zero are slightly different
> DT-969 Set container count for pollpusher and offender search to 0 in test/preprod/prod

- delius-test/sub-projects/delius-core.tfvars
Request summary from Chris Pugh (https://mojdt.slack.com/archives/G01DWRX6Y07/p1605014483006000):
We’re part of a team building tools to support Offender Managers carrying out supervision of community sentences, which is currently carried out in Delius. We want to have team access to the a Delius environment that’s like Live but with synthetic data in it, so that we can understand more about how the current process works, to inform our designs
> Enable access from the DXW VPN

- common-prod/common.tfvars
- common/common.tfvars
Provisioned IOPS is no longer required for the root volume, as the LDAP data is now hosted on EFS. This should result in an EBS cost reduction.
> ALS-2057 - Added configuration for LDAP EFS + reduced specs for root EBS volume

- common-prod/common.tfvars
to reduce noise due to response time warnings intermittently firing after 23:00
> Extend quiet period for Prod Delius-Core slack alerts

- common-prod/common.tfvars
Following performance test results, and risk/cost evaluation here: [ALS-1712](https://jira.engineering-dev.probation.hmpps.dsd.io/browse/ALS-1712)
> ALS-1712 Set ActiveMQ EFS throughput to 16MiB/s

- common-prod/common.tfvars
- common/common.tfvars
This will instead be implemented by pulling the Bastion IPs from Terraform state, in the hmpps-delius-core-terraform and hmpps-mis-terraform-repo projects.
> Removed Bastion IPs from common user access CIDRs.

- common-prod/common.tfvars
- common/common.tfvars
due to the shift in CPU/Memory usage caused by adding the WebLogic services. This usage should be monitored going forward by observing the ratio between MemoryReservation and CPUReservation on the cluster.
Also moved some config items around so it reads better.
> Use r5 instance types for the ECS cluster

- common-prod/common.tfvars
A full contact index takes up ~650GB, and the max storage is currently 128*6 = 768GB. This is being increased to ~1.5TB, so that we can run two concurrent indices - for the purposes of re-indexing during live service.
> Increase storage size for the contact-search to handle secondary index

- delius-stage/sub-projects/delius-core.tfvars
HMPPS Auth can either connect to preprod or stage when authentication users; both environments are equally valid so this gives flexibility depending on the specific testing required
> Add preprod hmpps auth access so that it can connect to stage

- common-prod/common.tfvars
This change means that 8CPU cores will be allocated to containers using those configs
> NIT-40 increase alf resource allocation in live envs

- common-prod/common.tfvars
- common/common.tfvars
IP ranges were pulled from https://github.com/ministryofjustice/moj-ip-addresses/blob/main/moj-cidr-addresses.yml
> DST-11176 Allow access from MOJ GlobalProtect + updated production access IP ranges

- common-prod/common.tfvars
This is to allow a single alfresco-content instance to handle expected load while we tested a resilient version of the implementation
> NIT-40 temporarily increase resource allocations

- delius-core-dev/sub-projects/iaps.tfvars
- delius-prod/sub-projects/iaps.tfvars
- delius-stage/sub-projects/iaps.tfvars
IAPS terraform pipeline failing because of a minor RDS error - Amazon Oracle RDS minor upgrade has put the Database ahead of the terraform code. To fix that error, we must change the version to match the current one for each environments.
> Fix RDS terraform error - change version to match the current one 

- delius-prod/sub-projects/alfresco.tfvars
This change allows us to control the backup policy with more granularity. There is no reason for longterm backups of non-prod environments
> NIT-90 optimise solr backup policy

- delius-core-dev/sub-projects/delius-core.tfvars
- delius-core-sandpit-2/sub-projects/delius-core.tfvars
- delius-core-sandpit/sub-projects/delius-core.tfvars
- delius-mis-dev/sub-projects/delius-core.tfvars
- delius-mis-test/sub-projects/delius-core.tfvars
- delius-perf/sub-projects/delius-core.tfvars
- delius-pre-prod/sub-projects/delius-core.tfvars
- delius-prod/sub-projects/delius-core.tfvars
- delius-stage/sub-projects/delius-core.tfvars
- delius-test/sub-projects/delius-core.tfvars
- delius-training-test/sub-projects/delius-core.tfvars
- delius-training/sub-projects/delius-core.tfvars
Work item https://dsdmoj.atlassian.net/browse/NIT-161
Related IaC: https://github.com/ministryofjustice/hmpps-oracle-database/pull/19
To apply this change, a further PR will be required to bump the version reference in the module call to the oracle-database module, e.g. here https://github.com/ministryofjustice/hmpps-delius-core-terraform/blob/main/database_failover/server-delius-db-1.tf#L12
This PR provides the additional data in changes made to the oracle-database terraform module (PR above)
The approach to changing data values was
- Make changes to configure delius-sandpit and delius-core-dev to use gp3 volumes (for both data and root) as opposed to io1
- Ensure that values for new variables for all other environments remain set for io1. (Further changes may adjust these)
> Adding delius-db params related to EBS volume types

- delius-core-dev/delius-core-dev.tfvars
A PR was raised for other delius envs to enable the auto stop-start of RDS instances - https://github.com/ministryofjustice/hmpps-env-configs/pull/2028/files
It looks like this still needs to be done in delius-core-dev, hence adding this rds_schedule = true line.
Work item: https://dsdmoj.atlassian.net/browse/NIT-170.
> Enable RDS startstop for delius-core-dev

- delius-pre-prod/ansible/group_vars/mis_standbydb1.yml
- delius-prod/ansible/group_vars/mis_standbydb1.yml
During overnight processing apply lag for MIS Standby may be up to 10 minutes.
This is monitored using OEM using Adaptive Thresholds which accommodate different overnight thresholds so we do not want a alert for a 30 second lag all day.
> Set Apply Lag Threshold for MIS Standby

- delius-prod/ansible/group_vars/misboe_primarydb.yml
Throttle PRDBOE Full Backup to prevent high CPU alert (since static time based monitoring thresholds not working in OEM 13.4)
> Throttle PRDBOE Full Backup

- delius-pre-prod/sub-projects/delius-core.tfvars
Change EBS volume type from io1 to gp3 type for delius-pre-prod env.
Ticket no. https://dsdmoj.atlassian.net/browse/NIT-241
> Delius DB EBS vol optimisation - delius-pre-prod env

- delius-training/sub-projects/delius-core.tfvars
Change EBS volume type from io1 to gp3 type for delius-training env.
Ticket no. https://dsdmoj.atlassian.net/browse/NIT-241
> Delius DB EBS vol optimisation - delius-training

- common-prod/common.tfvars
- delius-pre-prod/sub-projects/alfresco.tfvars
- delius-prod/sub-projects/alfresco.tfvars
- delius-stage/sub-projects/alfresco.tfvars
currently over-provisioned. halving will still live a lot of headroom based on observed metrics
> NIT-243 halve provisioned iops for alfresco DBs

- delius-prod/sub-projects/delius-core.tfvars
Changes EBS volumes attached to DB instances in delius-prod:
- volume type from io1 to gp3 type
- set IOPS allocation to 4000
- set throughput to 1000
Ticket no. https://dsdmoj.atlassian.net/browse/NIT-241
> Delius DB EBS vol optimisation - delius-prod

- delius-test/ansible/group_vars/delius_primarydb.yml
Required to handle UMT connection surge during Serenity Tests.
> Increase AWS Test process limit from 700 to 1000

- delius-prod/ansible/group_vars/delius_primarydb.yml
Read Only users are not normally created on Production.   This is a special request from Michael and approved by Nic to allow this access for Unilink users who already have R/W access via the DELIUS_APP_SCHEMA account.   This account should be used by default to limit unintentional production changes.   _RO accounts are used instead of _SRO accounts in case of a need to investigate issues during a release or other time when Standby may not be in sync.
> Add Unilink Read Only Users to Prod

- delius-core-dev/delius-core-dev.tfvars
- delius-mis-dev/delius-mis-dev.tfvars
- delius-test/delius-test.tfvars
- delius-training/delius-training.tfvars
Level 0 backups of lower environments should run on Wednesdays instead of Mondays to reduce impact of bank holiday shutdowns in those environments.
Note that there is still the possibility for level 0 backups to be skipped during Christmas or New Year holidays in some years, but the overall number of skipped runs will be smaller.
> Move Level 0 Backups to Wednesdays to Reduce Bank Holiday Impacts

- delius-prod/delius-prod.tfvars
Stop lambda function in prod while investigating options to fix the issue.
Ticket no. https://dsdmoj.atlassian.net/browse/NIT-716
> Disable lambda function which resizes ETL ec2 instance

- common-prod/common.tfvars
- delius-prod/sub-projects/delius-core.tfvars
Note: EC2 host limit is 4GB (type=c5.large).
> Set DSS heap size to 2.5GB + increase container memory limit to 3.5GB.

- delius-prod/sub-projects/delius-core.tfvars
> Enable Merge API only

- ansible/group_vars/all.yml
RBAC is uplifted by integrations pipeline. this is to keep the version dash board right.
> RBAC => 6.3.8
